import * as ElementPlusIconsVue from '@element-plus/icons-vue';
import {
  ElButton,
  ElCol,
  ElConfigProvider,
  ElContainer,
  ElDatePicker,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElForm,
  ElFormItem,
  // ElHeader,
  ElIcon,
  ElInput,
  ElMenu,
  ElMenuItem,
  ElOption,
  ElPagination,
  ElRow,
  ElScrollbar,
  ElSelect,
  ElSubMenu,
  ElTable,
  ElTableColumn,
  ElTimePicker,
  ElTimeSelect,
  ElTreeSelect,
  ElLoading,
  ElBreadcrumb,
  ElBreadcrumbItem,
  // ElUpload,
  ElBadge,
  // ElMain,
  /*    ElDrawer, */
  // ElDivider,
  ElCheckbox,
  ElTabs,
  ElRadio,
  /*    ElColorPicker, */
  ElSwitch,
  ElPopover,
  // ElCascader,
  ElDialog,
  ElImage,
  ElInputNumber,
  ElSelectV2,
  // ElSpace,
  // ElLink,
  // ElCard,
  ElEmpty,
  ElTag,
  ElProgress,
  ElAutoResizer,
  // ElTableV2,
  ElTree,
  // ElCollapseItem,
  // ElCollapse,
  // ElTimeline,
  ElTooltip,
  ElSlider
} from 'element-plus';
import type { App } from 'vue';
const components: any = [
  ElButton,
  ElCol,
  ElConfigProvider,
  ElContainer,
  ElDatePicker,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElForm,
  ElFormItem,
  // ElHeader,
  ElIcon,
  ElInput,
  ElMenu,
  ElMenuItem,
  ElOption,
  ElPagination,
  ElRow,
  ElScrollbar,
  ElSelect,
  ElSubMenu,
  ElTable,
  ElTableColumn,
  ElTimePicker,
  ElTimeSelect,
  ElTreeSelect,
  ElLoading,
  ElBadge,
  ElBreadcrumb,
  ElBreadcrumbItem,
  // ElUpload,
  // ElMain,
  ElCheckbox,
  ElTabs,
  ElRadio,
  ElSwitch,
  ElPopover,
  // ElCascader,
  ElDialog,
  ElImage,
  ElInputNumber,
  ElSelectV2,
  // ElSpace,
  // ElLink,
  // ElCard,
  // ElDivider,
  ElEmpty,
  ElTag,
  ElProgress,
  ElAutoResizer,
  // ElTableV2,
  ElTree,
  // ElCollapse,
  // ElCollapseItem,
  // ElTimeline,
  ElTooltip,
  ElSlider
];
const install = (app: App) => {
  components.forEach((item: any) => {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
    app.use(item);
  });
  for (const [key, component] of Object.entries(ElementPlusIconsVue)) {
    app.component(key, component);
  }
};
export default { install };
